collections:
  - name: devopsarr.sonarr
    version: 1.1.1
    type: galaxy
  - name: devopsarr.radarr
    version: 1.1.0
    type: galaxy
  - name: devopsarr.lidarr
    version: 1.0.0
    type: galaxy
  - name: devopsarr.readarr
    version: 0.1.0
    type: galaxy
  - name: devopsarr.whisparr
    version: 0.1.0
    type: galaxy
  - name: devopsarr.prowlarr
    version: 0.1.0
    type: galaxy